name: car-park-frd

image: node:latest

stages:
  - react-testing
  - react-build
  - react-deploy

react-build:
  stage: react-build
  before_script:
    - cd car-park-fn/
  only:
    - production
  script:
    - yarn install
    - GENERATE_SOURCEMAP=false yarn build
  artifacts:
    paths:
    - car-park-fn/build




  react-deploy:
    image: python:3.6
    stage: react-deploy
    before_script:
      - pip install awscli
    dependencies:
      - react-build
    only:
      - production
    script:
      - aws s3 sync car-park-fn/build s3://${BUCKET_NAME} --delete
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths "/*"